version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/watersmart
      - SECRET_KEY=development-secret-key
      - JWT_SECRET_KEY=development-jwt-secret
    depends_on:
      - db
    volumes:
      - ./:/app
    command: python app.py

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=watersmart
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: